### ISSUE TITLE
G\DB::get with OR clause only gives 1 result

### ISSUE THREAD

**Issue by rainje** [chevereto/G-Library#11]
Here's the sql request i'm trying to do:

SELECT * FROM `table` WHERE field = 1 OR field = 2;

It works fine in mysql, gives me two rows.

When i'm trying to use G\DB::get:

G\DB::get('`table`', ['field' => 1, 'field' => 2], 'OR'); 

I get one array, [0] and that's all (with field = 2 data). Am I doing something wrong here? :)

I tried to set the limit to 2, doesnt work either.

BTW: gbackslash website seems out of order.

**Comment by chevereto** [comment]
You should debug the query at class.db.php to see what query is G\DB doing for you.

**Comment by rainje** [comment]
Here's the debug for the query:
SELECT * FROM `table` WHERE `field`=:value

Tried with 'AND' and same query. maybe it doesnt like the fact i'm doing two where on a single field?

**Comment by rainje** [comment]
Aight I get it, issue with the array having two keys with the same name so the second key's value overwrite the first one. That's not a bug it's just you can't do what I want with arrays so i'll just use the usual way :)

Duh sorry.

**Comment by chevereto** [comment]
The only workaround will be to add incremental ids to the binded values, instead of :key :value the system should use :key1 :value1

**Comment by rainje** [comment]
Yeah, no need to get complicated that's why i'm using G\, i'm fine with $db->query ;)
