### ISSUE TITLE
Include template system

### ISSUE THREAD

**Issue by marco1705** [Chevereto/g-library#13]
Maybe it would be possible to include a template system like Smarty or Dwoo. It would be much easier to handle templates, because you don't have to switch between php and html each time.

**Comment by rodolfoberrios** [comment]
G\ sticks to PHP HTML templates, no plans to change that for Smarty. 

I've plans to add Twig but I've to test it out and see if works good and if there are no performance impact. Main problem with PHP is that template systems needs to be somehow "compiled" or rely in cache to don't stress performance so it needs to be tested first.

**Comment by marco1705** [comment]
That's also great. It's just because the PHP HTML templates are confusing if you have a lot of code in there. The template syntax is more pretty and easier to read.

**Comment by rodolfoberrios** [comment]
Keep in mind that non-PHP templates:

1. Uses more system resources than pure PHP templates so a built-in cache or compiling is a must.
2. Are limited to simple statements (if, else, for).

Basically a non-PHP template systems took non-PHP code and convert it to valid PHP code so you can get the same performance of a pure PHP template without the mess of PHP. Something like change this <?php echo $code; ?>to this {{code}} for your eyes.

So like I said, thing is to find a system that fills in and that don't add too much load to this.
